name: 'Cat Action Helfmanr'
description: 'Cats a file'
inputs:
  filename: 
    description: 'The File Name'
    required: true
runs:
  using: "composite"
  steps:
    - run: cat ${{ inputs.filename }}
      shell: bash
    
